### ISSUE TITLE
Assign v-model

### ISSUE THREAD

**Issue by kyoukhana** [gerardreches/vue-qrcode-component#1]
I was wondering how do I dynamically assign a value to the component.  v-model so that I bind a dynamic value to it.

**Comment by gerardreches** [comment]
I will try to implement this option tomorrow, thanks!

**Comment by gerardreches** [comment]
@kyoukhana 

Added in [v2.1.0](https://github.com/gerardreches/vue-qrcode-component/releases/tag/v2.1.0). I also added extra [documentation](https://gerardreches.github.io/vue-qrcode-component/).

Now you can simply use `v-bind:` on the _text_ prop and pass a variable attached to a v-model.

```html
<input type="text" v-model="message">
<qr-code :text="message"></qr-code>
```
