### ISSUE TITLE
Visible text

### ISSUE THREAD

**Issue by nik-endozo** [gerardreches/vue-qrcode-component#13]
Can you add an option that you can disable tooltip. It shows tooltip when cursor is hovered into the QR.

**Comment by gerardreches** [comment]
Hi @nik-endozo ,

Could you show me a screenshot? How is that tooltip generated?

I have never added any feature to this component to show a tooltip on top of the generated QR code, and there should be no tooltip.

Regards,
Gerard

**Comment by gerardreches** [comment]
I'll be closing this issue since I haven't received any answer. Feel free to open it again if the issue reappears.
