### ISSUE TITLE
Vue 3 question

### ISSUE THREAD

**Issue by DomeT99** [gerardreches/vue-qrcode-component#18]
Hi!

I read the documentation about this library and I have not found version compatibility specifications. 
The question is: is the library written only for Vue 2 or also for Vue 3?

Thanks for the answer

**Comment by gerardreches** [comment]
Hi @DomeT99 ,

The library was written for Vue 2. I haven't used Vue for some time now, so I'm not up to date. While it was written for Vue 2, it may be that it still works with Vue 3. I'm not sure if they made any changes to Vue 3 that would make it incompatible with components built for Vue 2.

This [StackOverflow question](https://stackoverflow.com/questions/64122089/how-can-i-use-vue2-old-component-vue-file-with-a-new-vue3-project) addresses this topic. It seems that there should be no issue using a Vue 2 component with Vue 3 😄

**Comment by DomeT99** [comment]
Hi @gerardreches,
I believe will try the library in a Vue 3 project to be sure.
Thank you for the answer! 😁
