### ISSUE TITLE
QR Code Not Generated for Strings of 192 to 217 Characters

### ISSUE THREAD

**Issue by Revanjin** [gerardreches/vue-qrcode-component#21]
We've observed that URLs or strings ranging from 192 to 217 characters fail to generate a QR code. The issue stems from a specific line in the code:

javascript
if(buffer.getLengthInBits()+4<=totalDataCount*8){buffer.put(0,4);}

The error encountered is:
Uncaught (in promise) Error: code length overflow. (1756>1056)

Furthermore, we confirmed this behavior on the website [Vue QR Code Component](https://gerardreches.github.io/vue-qrcode-component/). Any input within the specified character range fails to produce a QR code.

**Comment by gerardreches** [comment]
Unfortunately this issue stems from the javascript library this component relies on, and there is no current alternative fork containing a solution.

Please report the issue at [the aforementioned repository](https://github.com/KeeeX/qrcodejs).
