### ISSUE TITLE
[Feature Request] Changing eyes shape to round / or others

### ISSUE THREAD

**Issue by LTFENG** [gerardreches/vue-qrcode-component#9]
Hi I would like to know is that possible to change the eyes of shape in qr code ?

**Comment by gerardreches** [comment]
Hi @LTFENG ,

Sorry, but this component is based on [davidshimjs/qrcodejs](https://github.com/davidshimjs/qrcodejs), which doesn't have such option, therefore I see no way to implement that feature in this component without changing it completely.
